// FoodDeliveryFrontend/src/app/components/auth/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="login-page">
      <!-- Header -->
      <header class="auth-header">
        <div class="container">
          <h1 class="logo" (click)="goHome()">🍕 FoodiHub</h1>
          <button class="nav-btn" (click)="goToRegister()">
            Don't have an account? Register
          </button>
        </div>
      </header>

      <div class="login-container">
        <div class="container">
          <div class="login-card">
            <div class="card-header">
              <h2>Welcome Back!</h2>
              <p>Login to continue your food journey</p>
            </div>

            <form class="login-form" (ngSubmit)="onSubmit()" #loginForm="ngForm">
              <div class="form-group">
                <label class="form-label">Email Address</label>
                <input 
                  type="email" 
                  class="form-control"
                  [(ngModel)]="email"
                  name="email"
                  placeholder="Enter your email"
                  required
                  email
                  #emailInput="ngModel"
                >
                <div class="error-message" *ngIf="emailInput.invalid && emailInput.touched">
                  Please enter a valid email address
                </div>
              </div>

              <div class="form-group">
                <label class="form-label">Password</label>
                <input 
                  type="password" 
                  class="form-control"
                  [(ngModel)]="password"
                  name="password"
                  placeholder="Enter your password"
                  required
                  #passwordInput="ngModel"
                >
                <div class="error-message" *ngIf="passwordInput.invalid && passwordInput.touched">
                  Password is required
                </div>
              </div>

              <div class="form-actions">
                <button type="submit" class="btn btn-primary" [disabled]="loginForm.invalid || logging">
                  <i class="fas fa-spinner fa-spin" *ngIf="logging"></i>
                  <i class="fas fa-sign-in-alt" *ngIf="!logging"></i>
                  <span *ngIf="!logging">Login</span>
                  <span *ngIf="logging">Logging in...</span>
                </button>
              </div>

              <div class="forgot-password">
                <a href="#" (click)="forgotPassword($event)">Forgot your password?</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .login-page {
      min-height: 100vh;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      display: flex;
      flex-direction: column;
    }

    .auth-header {
      background: rgba(255, 255, 255, 0.1);
      backdrop-filter: blur(10px);
      border-bottom: 1px solid rgba(255, 255, 255, 0.2);
    }

    .auth-header .container {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 15px 20px;
    }

    .logo {
      font-size: 2rem;
      color: white;
      margin: 0;
      font-weight: 700;
      cursor: pointer;
      text-shadow: 0 2px 10px rgba(0, 0, 0, 0.3);
    }

    .nav-btn {
      background: rgba(255, 255, 255, 0.2);
      border: 2px solid rgba(255, 255, 255, 0.3);
      color: white;
      padding: 10px 20px;
      border-radius: 25px;
      cursor: pointer;
      transition: all 0.3s ease;
      font-weight: 500;
    }

    .nav-btn:hover {
      background: rgba(255, 255, 255, 0.3);
    }

    .login-container {
      flex: 1;
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 40px 20px;
    }

    .login-card {
      background: white;
      border-radius: 20px;
      overflow: hidden;
      box-shadow: 0 20px 60px rgba(0, 0, 0, 0.2);
      width: 100%;
      max-width: 450px;
    }

    .card-header {
      background: linear-gradient(135deg, #ff6b6b, #ee5a24);
      color: white;
      padding: 40px;
      text-align: center;
    }

    .card-header h2 {
      margin: 0 0 10px 0;
      font-size: 2rem;
      font-weight: 600;
    }

    .card-header p {
      margin: 0;
      opacity: 0.9;
      font-size: 1.1rem;
    }

    .login-form {
      padding: 40px;
    }

    .form-group {
      margin-bottom: 25px;
    }

    .form-label {
      display: block;
      margin-bottom: 8px;
      font-weight: 600;
      color: #333;
    }

    .form-control {
      width: 100%;
      padding: 15px;
      border: 2px solid #e1e5e9;
      border-radius: 10px;
      font-size: 16px;
      transition: border-color 0.3s ease;
    }

    .form-control:focus {
      outline: none;
      border-color: #ff6b6b;
      box-shadow: 0 0 0 3px rgba(255, 107, 107, 0.1);
    }

    .error-message {
      color: #dc3545;
      font-size: 0.9rem;
      margin-top: 5px;
    }

    .form-actions {
      margin-bottom: 20px;
    }

    .btn {
      width: 100%;
      padding: 15px;
      font-size: 1.1rem;
      font-weight: 600;
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 10px;
    }

    .forgot-password {
      text-align: center;
    }

    .forgot-password a {
      color: #ff6b6b;
      text-decoration: none;
      font-weight: 500;
    }

    .forgot-password a:hover {
      text-decoration: underline;
    }

    @media (max-width: 768px) {
      .auth-header .container {
        flex-direction: column;
        gap: 15px;
      }
      
      .login-container {
        padding: 20px;
      }
      
      .card-header,
      .login-form {
        padding: 30px 20px;
      }
    }
  `]
})
export class LoginComponent implements OnInit {
  email = '';
  password = '';
  logging = false;

  constructor(private router: Router) {}

  ngOnInit() {
    // Any initialization logic
  }

  onSubmit() {
    if (!this.email || !this.password) return;
    
    this.logging = true;
    
    // Simulate login API call
    setTimeout(() => {
      this.logging = false;
      // Simulate successful login
      this.router.navigate(['/payment']);
    }, 2000);
  }

  forgotPassword(event: Event) {
    event.preventDefault();
    alert('Password reset functionality will be implemented in the backend integration');
  }

  goToRegister() {
    this.router.navigate(['/register']);
  }

  goHome() {
    this.router.navigate(['/welcome']);
  }
}

// foodie-hub-frontend/src/components/auth/Login.tsx
import React, { useState } from 'react';
import styled from 'styled-components';
import { Phone, Lock, ArrowRight } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import { useNavigate } from 'react-router-dom';

const LoginContainer = styled.div`
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  padding: 20px;
`;

const LoginCard = styled.div`
  background: white;
  border-radius: 20px;
  padding: 40px;
  box-shadow: 0 20px 40px rgba(0, 0, 0, 0.1);
  width: 100%;
  max-width: 400px;
`;

const Title = styled.h1`
  text-align: center;
  margin-bottom: 30px;
  color: #333;
  font-size: 28px;
  font-weight: 700;
`;

const Subtitle = styled.p`
  text-align: center;
  margin-bottom: 30px;
  color: #666;
  font-size: 16px;
`;

const InputGroup = styled.div`
  margin-bottom: 20px;
  position: relative;
`;

const InputIcon = styled.div`
  position: absolute;
  left: 15px;
  top: 50%;
  transform: translateY(-50%);
  color: #999;
`;

const Input = styled.input`
  width: 100%;
  padding: 15px 15px 15px 50px;
  border: 2px solid #e1e5e9;
  border-radius: 10px;
  font-size: 16px;
  transition: border-color 0.3s ease;

  &:focus {
    outline: none;
    border-color: #667eea;
  }

  &:disabled {
    background-color: #f5f5f5;
    cursor: not-allowed;
  }
`;

const Button = styled.button`
  width: 100%;
  padding: 15px;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  border: none;
  border-radius: 10px;
  font-size: 16px;
  font-weight: 600;
  cursor: pointer;
  transition: transform 0.2s ease;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 10px;

  &:hover:not(:disabled) {
    transform: translateY(-2px);
  }

  &:disabled {
    opacity: 0.6;
    cursor: not-allowed;
    transform: none;
  }
`;

const SecondaryButton = styled(Button)`
  background: transparent;
  color: #667eea;
  border: 2px solid #667eea;
  margin-top: 10px;

  &:hover:not(:disabled) {
    background: #667eea;
    color: white;
  }
`;

const ErrorMessage = styled.div`
  background: #fee;
  color: #c33;
  padding: 10px;
  border-radius: 8px;
  margin-bottom: 20px;
  text-align: center;
  font-size: 14px;
`;

const SuccessMessage = styled.div`
  background: #efe;
  color: #3c3;
  padding: 10px;
  border-radius: 8px;
  margin-bottom: 20px;
  text-align: center;
  font-size: 14px;
`;

const LinkText = styled.p`
  text-align: center;
  margin-top: 20px;
  color: #666;
  
  a {
    color: #667eea;
    text-decoration: none;
    font-weight: 600;
    
    &:hover {
      text-decoration: underline;
    }
  }
`;

const Login: React.FC = () => {
  const [phoneNumber, setPhoneNumber] = useState('');
  const [otp, setOtp] = useState('');
  const [step, setStep] = useState<'phone' | 'otp'>('phone');
  const [otpSent, setOtpSent] = useState(false);
  const [generatedOtp, setGeneratedOtp] = useState('');
  
  const { generateOtp, login, isLoading, error, clearError } = useAuth();
  const navigate = useNavigate();

  const handleGenerateOtp = async (e: React.FormEvent) => {
    e.preventDefault();
    clearError();
    
    if (!phoneNumber.trim()) {
      return;
    }

    try {
      const otpCode = await generateOtp(phoneNumber);
      setGeneratedOtp(otpCode);
      setStep('otp');
      setOtpSent(true);
    } catch (error) {
      console.error('Failed to generate OTP:', error);
    }
  };

  const handleVerifyOtp = async (e: React.FormEvent) => {
    e.preventDefault();
    clearError();
    
    if (!otp.trim()) {
      return;
    }

    try {
      await login(phoneNumber, otp);
      navigate('/');
    } catch (error) {
      console.error('Failed to verify OTP:', error);
    }
  };

  const handleBackToPhone = () => {
    setStep('phone');
    setOtp('');
    setOtpSent(false);
    setGeneratedOtp('');
    clearError();
  };

  return (
    <LoginContainer>
      <LoginCard>
        <Title>Welcome to FoodieHub</Title>
        
        {step === 'phone' ? (
          <>
            <Subtitle>Enter your phone number to get started</Subtitle>
            
            {error && <ErrorMessage>{error}</ErrorMessage>}
            
            <form onSubmit={handleGenerateOtp}>
              <InputGroup>
                <InputIcon>
                  <Phone size={20} />
                </InputIcon>
                <Input
                  type="tel"
                  placeholder="Enter phone number"
                  value={phoneNumber}
                  onChange={(e) => setPhoneNumber(e.target.value)}
                  disabled={isLoading}
                  required
                />
              </InputGroup>
              
              <Button type="submit" disabled={isLoading || !phoneNumber.trim()}>
                {isLoading ? 'Sending...' : 'Send OTP'}
                <ArrowRight size={20} />
              </Button>
            </form>
          </>
        ) : (
          <>
            <Subtitle>Enter the OTP sent to {phoneNumber}</Subtitle>
            
            {error && <ErrorMessage>{error}</ErrorMessage>}
            {otpSent && !error && (
              <SuccessMessage>
                OTP sent successfully! Demo OTP: {generatedOtp}
              </SuccessMessage>
            )}
            
            <form onSubmit={handleVerifyOtp}>
              <InputGroup>
                <InputIcon>
                  <Lock size={20} />
                </InputIcon>
                <Input
                  type="text"
                  placeholder="Enter OTP"
                  value={otp}
                  onChange={(e) => setOtp(e.target.value)}
                  disabled={isLoading}
                  maxLength={6}
                  required
                />
              </InputGroup>
              
              <Button type="submit" disabled={isLoading || !otp.trim()}>
                {isLoading ? 'Verifying...' : 'Verify OTP'}
                <ArrowRight size={20} />
              </Button>
              
              <SecondaryButton type="button" onClick={handleBackToPhone} disabled={isLoading}>
                Back to Phone Number
              </SecondaryButton>
            </form>
          </>
        )}
        
        <LinkText>
          Don't have an account? <a href="/register">Sign up here</a>
        </LinkText>
      </LoginCard>
    </LoginContainer>
  );
};

export default Login;
